#!/bin/bash

echo -n "Drag and drop an image file here and press return:  "
read -e WLPR;
function change_wallpaper
{
    defaults write com.apple.desktop Background "{default = {ImageFilePath='$WLPR'; };}"; 
    killall Dock
}
change_wallpaper
